name: Aging
on:
  schedule:
    - cron: "00 12 24 09 *" # My Bday! :)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: Run linting
        run: uvx ruff check

      - name: Aging
        working-directory: ./.github/scripts
        run: uv run aging
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
